; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F446RE]
platform = ststm32
board = genericSTM32F446RE
framework = stm32cube
debug_tool = stlink
upload_protocol = stlink
monitor_speed = 115200
build_flags =
	-Ilib/FreeRTOS/portable/GCC/ARM_CM4F
	-Iinclude/app
	-Iinclude/cubemx
	-Ilib/FreeRTOS/CMSIS_RTOS_V2

	-mcpu=cortex-m4
	-mthumb
	-mfpu=fpv5-sp-d16
	-mfloat-abi=hard


    ;CMSIS-DSP
    -DARM_MATH_CM4
    -larm_cortexM4lf_math
extra_scripts = SetFlags.py
